version: '3.1'

services:

  ghost:
    image: ghost:alpine
    restart: always
    ports:
      - 8080:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: ${MARIADB_USER}
      database__connection__password: ${MARIADB_PASSWORD}
      database__connection__database: ${MARIADB_DATABASE}
      url: http://localhost:8080

  db:
    image: mariadb:latest
    restart: always
    volumes:
        - "./data/mariadb:/var/lib/mysql"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
